# Correction modes configuration
vrs-dynamic-move-thresh-m = 1000
auto-vrs-min-fixed-bls    = 2
auto-mac-min-fixed-bls    = 3
auto-fkp-min-stations     = 3

# Source RINEX OBS: daily file per addsource station
source-rinex-enable       = 1
source-rinex-dir          = build/source_rinex
# OBS: {STATION}_{YYYYMMDD}.obs
